In [1]:
#assignment 65

ans 1:To solve this problem, we can use Bayes' theorem, which states that the probability of an event A given event B is equal to the probability of event B given event A, multiplied by the probability of event A, divided by the probability of event B.

Let's define the events as follows:
A = an employee is a smoker
B = an employee uses the health insurance plan

We want to find the probability of A given B, i.e., P(A|B). We know that P(B) = 0.7 (given in the problem statement) and that P(A|B) = 0.4 (also given in the problem statement). We need to find P(B|A), i.e., the probability that an employee uses the health insurance plan given that they are a smoker.

We can use the formula as follows:

P(B|A) = P(A|B) * P(B) / P(A)

To find P(A), we need to use the law of total probability:

P(A) = P(A|B) * P(B) + P(A|B') * P(B')

where B' is the complement of B (i.e., an employee does not use the health insurance plan). We know that P(A|B') = 0 (since non-users of the health insurance plan cannot be smokers), so we can simplify the equation as:

P(A) = P(A|B) * P(B)

Now we can substitute the values we have:

P(B|A) = P(A|B) * P(B) / P(A)
= 0.4 * 0.7 / (0.4 * 0.7)
= 0.4

Therefore, the probability that an employee is a smoker given that he/she uses the health insurance plan is 0.4 or 40%.

ans 2:Bernoulli Naive Bayes and Multinomial Naive Bayes are two variations of the Naive Bayes algorithm that are commonly used in text classification tasks. Here are the differences between the two:

Data Representation: Bernoulli Naive Bayes assumes binary data, where each feature is either present or absent. Multinomial Naive Bayes, on the other hand, assumes count data, where each feature represents the number of times it occurs in a document.

Feature Occurrence: In Bernoulli Naive Bayes, a feature that occurs multiple times in a document is considered only once. In Multinomial Naive Bayes, the frequency of each feature is taken into account.

Feature Independence: Both algorithms assume that the features (words) in a document are independent of each other. However, Bernoulli Naive Bayes assumes that the absence or presence of a feature is independent of the presence or absence of other features, while Multinomial Naive Bayes assumes that the occurrence of a feature is independent of the occurrence of other features, given the class variable.

Application: Bernoulli Naive Bayes is suitable for text classification tasks where the goal is to distinguish between two classes, such as spam vs. non-spam emails. Multinomial Naive Bayes is commonly used for text classification tasks where the goal is to distinguish between more than two classes, such as sentiment analysis or topic classification.

ans 3: In Bernoulli Naive Bayes, missing values can be handled in different ways depending on the implementation. Here are some common methods:

Ignore the missing values: This is the simplest approach, where any missing values in the data are simply ignored. This approach is often used when the percentage of missing values is small and is unlikely to have a significant impact on the classification accuracy.

Treat missing values as a separate category: In this approach, a missing value is treated as a separate category, which is different from both 0 (the feature is absent) and 1 (the feature is present). This approach can be useful when missing values are not random and may contain some useful information.

Impute the missing values: In this approach, missing values are replaced with estimated values based on the available data. One common method for imputing missing values in Bernoulli Naive Bayes is to replace them with the class-specific mean or mode of the feature. Another approach is to use more sophisticated methods such as k-nearest neighbor imputation or matrix factorization.

It's important to note that the choice of method for handling missing values can have a significant impact on the classification accuracy. Therefore, it's important to carefully evaluate the performance of different methods on a validation dataset to choose the best approach for the specific task at hand.

ans 4: Gaussian Naive Bayes can be used for multi-class classification. The algorithm can be extended to handle more than two classes by using the "one-vs-all" (also known as "one-vs-rest") approach.

In the one-vs-all approach, we build one binary classifier for each class, where the positive class is the class of interest and the negative class includes all other classes. During classification, each classifier predicts the probability that the input belongs to its positive class, and the class with the highest probability is chosen as the final prediction.

For example, suppose we have a dataset with three classes A, B, and C. To classify a new instance, we would train three Gaussian Naive Bayes classifiers: one to distinguish A from B and C, one to distinguish B from A and C, and one to distinguish C from A and B. Each classifier would output a probability that the instance belongs to its positive class, and we would choose the class with the highest probability as the final prediction.

It's important to note that the one-vs-all approach can be less accurate than other multi-class classification algorithms such as multinomial Naive Bayes or logistic regression, especially when the classes are imbalanced or there is overlap between the classes. However, Gaussian Naive Bayes with the one-vs-all approach can still be a useful and simple method for multi-class classification, especially when the number of classes is small.

In [3]:
import pandas as pd
import numpy as np

In [12]:
df=pd.read_csv('spambase.data')
df.head()

,0,0.64,0.64.1,0.1,0.32,0.2,0.3,0.4,0.5,0.6,...,0.41,0.42,0.43,0.778,0.44,0.45,3.756,61,278,1
0,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.00,0.132,0.0,0.372,0.180,0.048,5.114,101,1028,1
1,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.01,0.143,0.0,0.276,0.184,0.010,9.821,485,2259,1
2,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.137,0.0,0.137,0.000,0.000,3.537,40,191,1
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.135,0.0,0.135,0.000,0.000,3.537,40,191,1
4,0.00,0.00,0.00,0.0,1.85,0.00,0.00,1.85,0.00,0.00,...,0.00,0.223,0.0,0.000,0.000,0.000,3.000,15,54,1

In [ ]:
from sklearn.naive_bayes import BernoulliNB, MultinomialNB, GaussianNB
from sklearn.model_selection import cross_val_score


target,data = df


# Bernoulli Naive Bayes
bnb = BernoulliNB()
bnb_scores = cross_val_score(bnb, data, target, cv=10, scoring=['accuracy', 'precision', 'recall', 'f1'])

# Multinomial Naive Bayes
mnb = MultinomialNB()
mnb_scores = cross_val_score(mnb, data, target, cv=10, scoring=['accuracy', 'precision', 'recall', 'f1'])

# Gaussian Naive Bayes
gnb = GaussianNB()
gnb_scores = cross_val_score(gnb, data.toarray(), target, cv=10, scoring=['accuracy', 'precision', 'recall', 'f1'])

# Report the performance metrics for each classifier
print("Bernoulli Naive Bayes:")
print("Accuracy:", bnb_scores['test_accuracy'].mean())
print("Precision:", bnb_scores['test_precision'].mean())
print("Recall:", bnb_scores['test_recall'].mean())
print("F1 Score:", bnb_scores['test_f1'].mean())

print("\nMultinomial Naive Bayes:")
print("Accuracy:", mnb_scores['test_accuracy'].mean())
print("Precision:", mnb_scores['test_precision'].mean())
print("Recall:", mnb_scores['test_recall'].mean())
print("F1 Score:", mnb_scores['test_f1'].mean())

print("\nGaussian Naive Bayes:")
print("Accuracy:", gnb_scores['test_accuracy'].mean())
print("Precision:", gnb_scores['test_precision'].mean())
print("Recall:", gnb_scores['test_recall'].mean())
print("F1 Score:", gnb_scores['test_f1'].mean())